auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  wal:
    enabled: false  # Disabling Write-Ahead Log since we're not using persistent storage
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory  # Store metadata in memory instead of disk
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m   # Flush chunks after 5 minutes of inactivity
  max_chunk_age: 1h       # Ensure all chunks are flushed after 1 hour
  chunk_target_size: 1048576  # 1MB chunk size
  chunk_retain_period: 30s  # Keep chunks for 30s before indexing
  max_transfer_retries: 0  # Disable chunk transfer retries

schema_config:
  configs:
    - from: 2022-10-01
      store: boltdb-shipper
      object_store: memory  # Store logs in memory (No filesystem)
      schema: v11
      index:
        prefix: index_
        period: 24h  # New index every 24 hours

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index  # Loki will store logs inside its container
    shared_store: memory  # Logs are stored in memory, not persistent storage

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # Logs older than 7 days will be rejected

chunk_store_config:
  max_look_back_period: 0s  # No limit on how far back queries can go

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s  # No automatic deletion of logs

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093  # Can be used for alerts
  ring:
    kvstore:
      store: inmemory
  enable_api: true
